export default Object.freeze({
  ACCOUNT: "Account Screen",
  ACCOUNTNAV: "Account",
  CALENDAR: "Calendar",
  CREATEGROUP: "New Group",
  LOGIN: "Login",
  MYGROUPS: "My Groups",
  REGISTER: "Register",
  SEARCH: "Search",
  SETTING: "Setting",
  WELCOME: "Welcome",
  ADD_POST: "AddPost",
  POSTS: "Posts",
  SELECTED: "Selected",
  GROUP: "Group Screen",
});
