export default Object.freeze({
  ACCOUNT: "Account Screen",
  ACCOUNTNAV: "Account",
  CALENDAR: "Calendar",
  CREATEGROUP: "New Group",
  MYGROUPS: "My Groups",
  SEARCHGROUPS: "Search Groups",
  GROUPOPTIONS: "Group Options",
  GROUPSNAV: "Groups Navigator",
  WELCOME: "Welcome",
  LOGIN: "Login",
  REGISTER: "Register",
  SETTING: "Settings Screen",
  SETTINGNAV: "Settings Navigator",
  ADDPOST: "AddPost",
  POSTS: "Posts",
  SELECTED: "Selected",
  IGNORED: "Ignored",
  GROUP: "Group Screen",
  EDITPROFILE: "Edit Profile",
});
